FROM golang:1.13

RUN apt-get update && apt-get install -qy libsystemd-dev git protobuf-compiler

WORKDIR /src
RUN git clone https://github.com/grafana/loki.git
WORKDIR /src/loki
RUN make clean && make BUILD_IN_CONTAINER=false promtail
