name: Docker Images CI

on:
  workflow_dispatch:
    inputs:
        docker_repo_name:
          default: "getcarrier/perfmeter"
          description: "Name of dockerhub repo"
          required: true
  create:
    tags: 
      - '*'
  push:
    branches: 
      - master

jobs:
  build_all_images_matrix:
    strategy:
      matrix:
        include:
          - dockerfile: 'Dockerfile_v_5_6_3'
            docker_tag: 'latest-5.6.3'
          - dockerfile: 'Dockerfile_v_5_5'
            docker_tag: 'latest-5.5'
          - dockerfile: 'Dockerfile_v_5_4_1'
            docker_tag: 'latest-5.4.1'
          - dockerfile: 'Dockerfile'
            docker_tag: 'latest-5.3'
          - dockerfile: 'Dockerfile_v_5_2_1'
            docker_tag: 'latest-5.2.1'
          - dockerfile: 'Dockerfile_v_5_2'
            docker_tag: 'latest-5.2'
          - dockerfile: 'Dockerfile_v_5_1_1'
            docker_tag: 'latest-5.1.1'
          - dockerfile: 'Dockerfile_v_5_1'
            docker_tag: 'latest-5.1'
          - dockerfile: 'Dockerfile_v_5_0'
            docker_tag: 'latest-5.0'
          - dockerfile: 'Dockerfile_v_4_0'
            docker_tag: 'latest-4.0'
    uses: ./.github/workflows/Docker image multiarch.yml
    with:
      dockerfile: ${{ matrix.dockerfile }}
      docker_tag: ${{ inputs.docker_repo_name || 'getcarrier/perfmeter' }}:${{ matrix.docker_tag }}
    secrets: inherit
